### ISSUE TITLE
Media (images) gone after add-on restart/update

### ISSUE THREAD

**Issue by Fred2024** [casperklein/homeassistant-addons#11] opened 2023-03-06 11:43 UTC
**Add-on name**
Netbox

**Describe the bug**
Media (images) gone after add-on update

**To Reproduce**
1. Go to 'Device Types'
2. Click on 'Device Types'
3. Click on a device
4. Click on 'edit'
5. Upload an image
6. Upgrade add-on and you will see the media folder is empty and the images are gone.

**Expected behavior**
The images should be migrated to the new volume

**Screenshots**
![image](https://user-images.githubusercontent.com/126654385/223100417-5f6fd50a-25a1-49b7-990c-76e747442baf.png)

**Additional context**
Is it possible to keep the images while updating the add-on?
Now with every update they are gone.

Thanks
Fred.

**Comment by casperklein** [comment] 2023-03-06 17:55
> Now with every update they are gone.

Is this a newly introduced regression / did this every work at some point?

I am wondering if the images are also lost, when you stop/start the addon.

**Comment by casperklein** [comment] 2023-03-06 21:49
>>  The images are not lost when you restart the add-on. Only after an update.

I cannot confirm this. I did a quick test and the image vanished after restarting the addon. This makes sense to me, because updating the addon and restarting the addon, both actions destroy the container and start a new one.

**Comment by casperklein** [comment] 2023-03-06 22:35
Fixed in version 3.4.5.1 👍

**Comment by casperklein** [comment] 2023-03-13 19:06
Version 3.4.6 has just been released. Please check if your problem is solved.

**Closed as completed** 2023-03-13 20:07 UTC
Labels: bug
